version: '3.8'

services:
  api:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - .env
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 1s
      timeout: 5s
      retries: 10
      start_period: 3s
